# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TravisCIDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  pod 'Fabric'
  pod 'Crashlytics'

  # Pods for TravisCIDemo

  target 'TravisCIDemo-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TravisCIDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

#target 'TravisCIDemo-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TravisCIDemo-tvOS

  #target 'TravisCIDemo-tvOSTests' do
    #inherit! :search_paths
    # Pods for testing
  #end

#end
