desc "Submit a new Beta Build to Crashlytics Beta"

lane :beta do |values|

    # Adjust the `build_type` and `flavor` params as needed to build the right APK for your setup

    emails = values[:test_email] ? values[:test_email] : ['guillaimejanssen@msn.com'] # You can list more emails here
    groups = values[:test_email] ? nil : nil # You can define groups on the web and reference them here

    gradle(task: "clean")
    gradle(
      task: "assembleRelease",
      #project_dir: "android/",
      properties: {
        'android.useDeprecatedNdk' => true,
        'android.injected.signing.store.file' => keystores/$TCD_RELEASE_STORE_FILE,
        'android.injected.signing.store.password' => $TCD_RELEASE_STORE_PASSWORD,
        'android.injected.signing.key.alias'=> $TCD_RELEASE_KEY_ALIAS,
        'android.injected.signing.key.password' => $TCD_RELEASE_KEY_PASSWORD
      }
    )

    supply(track: 'internal')
 
    crashlytics(
      api_token: '03219a875bcdc17c29e6a850f5d6e102ec3ece50',
      build_secret: 'ead4e396916ee1c3efae37e815829fbd56b8ba4a1da3963cfa830662beeabe68',
      emails: emails,
      groups: groups,
      debug: true,
      notes: 'Distributed with fastlane', # Check out the changelog_from_git_commits action
      notifications: true  # Should this distribution notify your testers via email?
    )
end