desc "Using Fastlane"

lane :beta do |values|

    desc "Pushing a new signed APK to Google Play Store, also adding Fabric Crashlytics"
    gradle(task: "clean")
    gradle(
      task: "assembleRelease",
      #project_dir: "android/",
      properties: {
        'android.useDeprecatedNdk' => true,
        'android.injected.signing.store.file' => '/home/travis/build/guillaime/RN-TravisCIDemo/android/keystores/keystore.keystore',
        'android.injected.signing.store.password' => 'password',
        'android.injected.signing.key.alias'=> 'traviscidemo',
        'android.injected.signing.key.password' => 'password'
      }
    )

    upload_to_play_store(track: 'internal')
    crashlytics(
      api_token: '$CRASHLYTICS_API_KEY',
      build_secret: '$CRASHLYTICS_BUILD_SECRET',
      debug: true,
      notifications: true
    )
end

lane :build do |values|

    desc "Trying to sign an APK"
    gradle(task: "clean")
    gradle(
      task: "assembleRelease",
      #project_dir: "android/",
      properties: {
        'android.useDeprecatedNdk' => true,
        'android.injected.signing.store.file' => '/home/travis/build/guillaime/RN-TravisCIDemo/android/keystores/keystore.keystore',
        'android.injected.signing.store.password' => 'password',
        'android.injected.signing.key.alias'=> 'traviscidemo',
        'android.injected.signing.key.password' => 'password'
      }
    )
end